version: '3.8'
services:
  quiz-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/quiz-management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=tr1nhtu@n
    depends_on:
      - db
      
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=quiz-management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tr1nhtu@n
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: