name: quiz_app_flutter
description: A Quiz App using Flutter with Bloc, and Clean Architecture

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^2.4.1
  easy_localization: ^3.0.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  dartz: 0.10.1
  retrofit: ^4.1.0
  logger: ^2.0.1

  # storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0

  copy_with_extension: ^5.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.2
  top_snackbar_flutter: ^3.1.0
  cached_network_image: ^3.2.3
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  connectivity_plus: ^4.0.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7

  #responsive
  flutter_screenutil: ^5.9.0
  flutter_gen: ^5.3.1

  infinite_scroll_pagination: ^4.0.0
  equatable: ^2.0.5
  shimmer: ^3.0.0
  event_bus: 2.0.0
  auto_route: ^8.0.3
  flutter_alice: ^1.1.1
  flutter_slidable: ^3.0.0
  mobile_scanner: ^3.5.7
  flutter_smart_dialog: ^4.9.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  freezed: ^2.5.1
  injectable_generator: ^2.1.6
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  copy_with_extension_gen: ^5.0.3
  flutter_gen_runner: ^5.3.2
  auto_route_generator: ^8.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 800
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 900

  assets:
    - assets/translations/
    - assets/env/
    - assets/images/
    - assets/svg/


